In [7]:
import pandas as pd

In [8]:
df = pd.read_csv('/Volumes/T9/2025_01_EPC_POSTCODES/W06000005-Flintshire_results.csv')

In [9]:
df.fillna(0)

,Unnamed: 0,count_buildings,mean_CURRENT_ENERGY_EFFICIENCY,postcode,mean_POTENTIAL_ENERGY_EFFICIENCY,mean_ENVIRONMENT_IMPACT_CURRENT,mean_ENVIRONMENT_IMPACT_POTENTIAL,mean_ENERGY_CONSUMPTION_CURRENT,mean_ENERGY_CONSUMPTION_POTENTIAL,mean_CO2_EMISSIONS_CURRENT,...,POTENTIAL_ENERGY_RATING_C,POTENTIAL_ENERGY_RATING_D,UPRN_SOURCE_Address Matched,UPRN_SOURCE_Energy Assessor,CURRENT_ENERGY_RATING_G,POTENTIAL_ENERGY_RATING_E,POTENTIAL_ENERGY_RATING_G,POTENTIAL_ENERGY_RATING_F,CURRENT_ENERGY_RATING_A,lad_code
0,0,22,60.36,CH5 2AB,79.00,59.45,77.68,297.41,160.82,3.37,...,18.181818,22.727273,81.818182,18.181818,0.000000,0.000000,0.000000,0.0,0.0,W06000005-Flintshire
1,1,15,62.40,CH7 2AW,80.33,58.20,78.27,273.47,142.87,4.04,...,26.666667,6.666667,80.000000,20.000000,0.000000,0.000000,0.000000,0.0,0.0,W06000005-Flintshire
2,2,4,56.50,CH8 7NG,76.75,51.25,73.25,323.00,170.25,4.75,...,75.000000,0.000000,75.000000,25.000000,0.000000,0.000000,0.000000,0.0,0.0,W06000005-Flintshire
3,3,22,41.32,CH8 8SU,73.05,38.05,67.27,348.27,159.27,8.28,...,31.818182,13.636364,72.727273,27.272727,9.090909,9.090909,4.545455,0.0,0.0,W06000005-Flintshire
4,4,22,64.86,CH7 4AB,79.95,61.18,77.50,248.50,142.59,3.80,...,22.727273,13.636364,63.636364,36.363636,0.000000,0.000000,0.000000,0.0,0.0,W06000005-Flintshire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4084,4084,2,37.00,LL12 9RN,68.00,34.00,58.50,257.50,120.50,21.00,...,50.000000,50.000000,0.000000,100.000000,0.000000,0.000000,0.000000,0.0,0.0,W06000005-Flintshire
4085,4085,2,68.50,CH8 8HS,80.00,62.50,75.50,206.50,134.00,5.10,...,50.000000,0.000000,0.000000,100.000000,0.000000,0.000000,0.000000,0.0,0.0,W06000005-Flintshire
4086,4086,3,90.00,CH7 6GZ,90.00,88.00,88.00,59.67,59.67,2.50,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,W06000005-Flintshire
4087,4087,6,75.17,CH5 2GX,75.17,77.83,77.83,176.17,176.17,1.37,...,100.000000,0.000000,0.000000,100.000000,0.000000,0.000000,0.000000,0.0,0.0,W06000005-Flintshire
4088,4088,9,88.78,CH7 2DS,88.78,90.00,90.00,85.44,85.44,0.71,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,W06000005-Flintshire

In [10]:
df

,Unnamed: 0,count_buildings,mean_CURRENT_ENERGY_EFFICIENCY,postcode,mean_POTENTIAL_ENERGY_EFFICIENCY,mean_ENVIRONMENT_IMPACT_CURRENT,mean_ENVIRONMENT_IMPACT_POTENTIAL,mean_ENERGY_CONSUMPTION_CURRENT,mean_ENERGY_CONSUMPTION_POTENTIAL,mean_CO2_EMISSIONS_CURRENT,...,POTENTIAL_ENERGY_RATING_C,POTENTIAL_ENERGY_RATING_D,UPRN_SOURCE_Address Matched,UPRN_SOURCE_Energy Assessor,CURRENT_ENERGY_RATING_G,POTENTIAL_ENERGY_RATING_E,POTENTIAL_ENERGY_RATING_G,POTENTIAL_ENERGY_RATING_F,CURRENT_ENERGY_RATING_A,lad_code
0,0,22,60.36,CH5 2AB,79.00,59.45,77.68,297.41,160.82,3.37,...,18.181818,22.727273,81.818182,18.181818,NaN,NaN,NaN,NaN,NaN,W06000005-Flintshire
1,1,15,62.40,CH7 2AW,80.33,58.20,78.27,273.47,142.87,4.04,...,26.666667,6.666667,80.000000,20.000000,NaN,NaN,NaN,NaN,NaN,W06000005-Flintshire
2,2,4,56.50,CH8 7NG,76.75,51.25,73.25,323.00,170.25,4.75,...,75.000000,NaN,75.000000,25.000000,NaN,NaN,NaN,NaN,NaN,W06000005-Flintshire
3,3,22,41.32,CH8 8SU,73.05,38.05,67.27,348.27,159.27,8.28,...,31.818182,13.636364,72.727273,27.272727,9.090909,9.090909,4.545455,NaN,NaN,W06000005-Flintshire
4,4,22,64.86,CH7 4AB,79.95,61.18,77.50,248.50,142.59,3.80,...,22.727273,13.636364,63.636364,36.363636,NaN,NaN,NaN,NaN,NaN,W06000005-Flintshire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4084,4084,2,37.00,LL12 9RN,68.00,34.00,58.50,257.50,120.50,21.00,...,50.000000,50.000000,NaN,100.000000,NaN,NaN,NaN,NaN,NaN,W06000005-Flintshire
4085,4085,2,68.50,CH8 8HS,80.00,62.50,75.50,206.50,134.00,5.10,...,50.000000,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,NaN,W06000005-Flintshire
4086,4086,3,90.00,CH7 6GZ,90.00,88.00,88.00,59.67,59.67,2.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,W06000005-Flintshire
4087,4087,6,75.17,CH5 2GX,75.17,77.83,77.83,176.17,176.17,1.37,...,100.000000,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,NaN,W06000005-Flintshire
4088,4088,9,88.78,CH7 2DS,88.78,90.00,90.00,85.44,85.44,0.71,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,W06000005-Flintshire

In [11]:
df.shape

(4089, 30)

In [12]:
cv = pd.read_csv('/Volumes/T9/2024_Data_downloads/2025_epc_database/all-domestic-certificates/domestic-W06000005-Flintshire/certificates.csv')

/Users/gracecolverd/opt/miniconda3/envs/ads4/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (34,37) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [13]:
cv['CURRENT_ENERGY_EFFICIENCY'].mean()

62.97263470852448

In [14]:
cv.POTENTIAL_ENERGY_EFFICIENCY.mean()

80.35395853646841

In [15]:
cv[cv['POSTCODE']=='CH7 2DS'][['CURRENT_ENERGY_EFFICIENCY', 'POTENTIAL_ENERGY_EFFICIENCY']].mean()

CURRENT_ENERGY_EFFICIENCY      88.777778
POTENTIAL_ENERGY_EFFICIENCY    88.777778
dtype: float64

In [16]:
cv[cv['POSTCODE']=='CH7 2DS']

,LMK_KEY,ADDRESS1,ADDRESS2,ADDRESS3,POSTCODE,BUILDING_REFERENCE_NUMBER,CURRENT_ENERGY_RATING,POTENTIAL_ENERGY_RATING,CURRENT_ENERGY_EFFICIENCY,POTENTIAL_ENERGY_EFFICIENCY,...,LOCAL_AUTHORITY_LABEL,CONSTITUENCY_LABEL,POSTTOWN,CONSTRUCTION_AGE_BAND,LODGEMENT_DATETIME,TENURE,FIXED_LIGHTING_OUTLETS_COUNT,LOW_ENERGY_FIXED_LIGHT_COUNT,UPRN,UPRN_SOURCE
62270,1f34c04bae37119f29961289475141e82bb1580ec2e6bd...,"2, Llys Alun",Brunswick Rd,NaN,CH7 2DS,10006666209,B,B,89,89,...,Flintshire,NaN,Buckley,2024,2024-10-28 12:32:36,Rented (social),12.0,NaN,NaN,NaN
62274,20c013d8280db21f8037d49a62f64d8244f827531f3292...,"8, Llys Alun",Brunswick Rd,NaN,CH7 2DS,10006729526,B,B,89,89,...,Flintshire,NaN,Buckley,2024,2024-10-28 12:34:42,Rented (social),15.0,NaN,NaN,NaN
62308,3cc3e64b8bf03b9bd3617631934138529e040a95e881bd...,"4, Llys Alun",Brunswick Rd,NaN,CH7 2DS,10006698562,B,B,88,88,...,Flintshire,NaN,Buckley,2024,2024-10-28 12:33:20,Rented (social),15.0,NaN,NaN,NaN
62405,89f62f2a32687e93b8dc0e7050ae4c06f909f8e7f72b3b...,"7, Llys Alun",Brunswick Rd,NaN,CH7 2DS,10006723707,B,B,90,90,...,Flintshire,NaN,Buckley,2024,2024-10-28 12:34:21,Rented (social),12.0,NaN,NaN,NaN
62429,98e7451cb540a0262a9aea4cba9235c7269f2276f5af05...,"3, Llys Alun",Brunswick Rd,NaN,CH7 2DS,10006685155,B,B,90,90,...,Flintshire,NaN,Buckley,2024,2024-10-28 12:32:59,Rented (social),12.0,NaN,NaN,NaN
62454,af407128390aeb0845d43cdb58a2a233bdd96d2d702c9f...,"5, Llys Alun",Brunswick Rd,NaN,CH7 2DS,10006708819,B,B,90,90,...,Flintshire,NaN,Buckley,2024,2024-10-28 12:33:41,Rented (social),12.0,NaN,NaN,NaN
62488,c9eb1ce016f287a7c45e6d14a89dba0196af1da0fdc29d...,"9, Llys Alun",Brunswick Rd,NaN,CH7 2DS,10006734548,B,B,87,87,...,Flintshire,NaN,Buckley,2024,2024-10-28 12:35:01,Rented (social),12.0,NaN,NaN,NaN
62497,d18d86004dce53633e63d9777a1d5017b528475862f27a...,"6, Llys Alun",Brunswick Rd,NaN,CH7 2DS,10006716992,B,B,89,89,...,Flintshire,NaN,Buckley,2024,2024-10-28 12:34:03,Rented (social),12.0,NaN,NaN,NaN
62517,e52fc1fd52fd04fec96a2af2b7e2a389d2497182db7c09...,"1, Llys Alun",Brunswick Rd,NaN,CH7 2DS,10006635368,B,B,87,87,...,Flintshire,NaN,Buckley,2024,2024-10-28 12:32:13,Rented (social),12.0,NaN,NaN,NaN

In [17]:
cv.columns.tolist()

['LMK_KEY',
 'ADDRESS1',
 'ADDRESS2',
 'ADDRESS3',
 'POSTCODE',
 'BUILDING_REFERENCE_NUMBER',
 'CURRENT_ENERGY_RATING',
 'POTENTIAL_ENERGY_RATING',
 'CURRENT_ENERGY_EFFICIENCY',
 'POTENTIAL_ENERGY_EFFICIENCY',
 'PROPERTY_TYPE',
 'BUILT_FORM',
 'INSPECTION_DATE',
 'LOCAL_AUTHORITY',
 'CONSTITUENCY',
 'COUNTY',
 'LODGEMENT_DATE',
 'TRANSACTION_TYPE',
 'ENVIRONMENT_IMPACT_CURRENT',
 'ENVIRONMENT_IMPACT_POTENTIAL',
 'ENERGY_CONSUMPTION_CURRENT',
 'ENERGY_CONSUMPTION_POTENTIAL',
 'CO2_EMISSIONS_CURRENT',
 'CO2_EMISS_CURR_PER_FLOOR_AREA',
 'CO2_EMISSIONS_POTENTIAL',
 'LIGHTING_COST_CURRENT',
 'LIGHTING_COST_POTENTIAL',
 'HEATING_COST_CURRENT',
 'HEATING_COST_POTENTIAL',
 'HOT_WATER_COST_CURRENT',
 'HOT_WATER_COST_POTENTIAL',
 'TOTAL_FLOOR_AREA',
 'ENERGY_TARIFF',
 'MAINS_GAS_FLAG',
 'FLOOR_LEVEL',
 'FLAT_TOP_STOREY',
 'FLAT_STOREY_COUNT',
 'MAIN_HEATING_CONTROLS',
 'MULTI_GLAZE_PROPORTION',
 'GLAZED_TYPE',
 'GLAZED_AREA',
 'EXTENSION_COUNT',
 'NUMBER_HABITABLE_ROOMS',
 'NUMBER_HEATED_ROOMS',
 'LOW_ENERGY_LIGHTING',
 'NUMBER_OPEN_FIREPLACES',
 'HOTWATER_DESCRIPTION',
 'HOT_WATER_ENERGY_EFF',
 'HOT_WATER_ENV_EFF',
 'FLOOR_DESCRIPTION',
 'FLOOR_ENERGY_EFF',
 'FLOOR_ENV_EFF',
 'WINDOWS_DESCRIPTION',
 'WINDOWS_ENERGY_EFF',
 'WINDOWS_ENV_EFF',
 'WALLS_DESCRIPTION',
 'WALLS_ENERGY_EFF',
 'WALLS_ENV_EFF',
 'SECONDHEAT_DESCRIPTION',
 'SHEATING_ENERGY_EFF',
 'SHEATING_ENV_EFF',
 'ROOF_DESCRIPTION',
 'ROOF_ENERGY_EFF',
 'ROOF_ENV_EFF',
 'MAINHEAT_DESCRIPTION',
 'MAINHEAT_ENERGY_EFF',
 'MAINHEAT_ENV_EFF',
 'MAINHEATCONT_DESCRIPTION',
 'MAINHEATC_ENERGY_EFF',
 'MAINHEATC_ENV_EFF',
 'LIGHTING_DESCRIPTION',
 'LIGHTING_ENERGY_EFF',
 'LIGHTING_ENV_EFF',
 'MAIN_FUEL',
 'WIND_TURBINE_COUNT',
 'HEAT_LOSS_CORRIDOR',
 'UNHEATED_CORRIDOR_LENGTH',
 'FLOOR_HEIGHT',
 'PHOTO_SUPPLY',
 'SOLAR_WATER_HEATING_FLAG',
 'MECHANICAL_VENTILATION',
 'ADDRESS',
 'LOCAL_AUTHORITY_LABEL',
 'CONSTITUENCY_LABEL',
 'POSTTOWN',
 'CONSTRUCTION_AGE_BAND',
 'LODGEMENT_DATETIME',
 'TENURE',
 'FIXED_LIGHTING_OUTLETS_COUNT',
 'LOW_ENERGY_FIXED_LIGHT_COUNT',
 'UPRN',
 'UPRN_SOURCE']

In [22]:
cv[['LODGEMENT_DATE', 'INSPECTION_DATE' ]]

      LODGEMENT_DATE INSPECTION_DATE
0         2008-11-06      2008-11-05
1         2012-11-28      2012-11-28
2         2010-04-27      2010-04-27
3         2010-03-02      2010-03-02
4         2009-03-06      2009-03-06
...              ...             ...
62556     2024-10-28      2024-10-26
62557     2024-10-16      2024-10-15
62558     2024-10-28      2024-10-25
62559     2024-10-03      2024-10-01
62560     2024-08-08      2024-08-07

[62561 rows x 2 columns]

In [19]:
cv.groupby('UPRN').count()

,LMK_KEY,ADDRESS1,ADDRESS2,ADDRESS3,POSTCODE,BUILDING_REFERENCE_NUMBER,CURRENT_ENERGY_RATING,POTENTIAL_ENERGY_RATING,CURRENT_ENERGY_EFFICIENCY,POTENTIAL_ENERGY_EFFICIENCY,...,ADDRESS,LOCAL_AUTHORITY_LABEL,CONSTITUENCY_LABEL,POSTTOWN,CONSTRUCTION_AGE_BAND,LODGEMENT_DATETIME,TENURE,FIXED_LIGHTING_OUTLETS_COUNT,LOW_ENERGY_FIXED_LIGHT_COUNT,UPRN_SOURCE
UPRN,,,,,,,,,,,,,,,,,,,,,
1.001355e+10,2,2,2,0,2,2,2,2,2,2,...,2,2,2,2,2,2,2,1,1,2
1.001369e+10,2,2,0,0,2,2,2,2,2,2,...,2,2,2,2,2,2,2,1,0,2
1.001369e+10,1,1,1,0,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,0,1
1.001369e+10,1,1,1,0,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
1.001369e+10,2,2,2,0,2,2,2,2,2,2,...,2,2,2,2,2,2,2,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2.000043e+11,2,2,2,0,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
2.000043e+11,1,1,1,0,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2.000043e+11,1,1,1,0,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2.000043e+11,2,2,2,0,2,2,2,2,2,2,...,2,2,2,2,2,2,2,0,0,2
2.000043e+11,1,1,1,1,1,1,1,1,1,1,...,1,1,0,1,1,1,1,1,0,1

In [23]:
# Assuming your dataframe is named 'df'
latest_entries = cv.sort_values('INSPECTION_DATE').groupby('UPRN').last().reset_index()

In [24]:
latest_entries.shape, cv.shape

((45243, 92), (62561, 92))